name: Solary-Economy
main: nuvemplugins.solaryeconomy.Main
version: 1.5
load: STARTUP
author: Sr_Edition
website: www.nuvemplugins.com
depend: [Vault, BukkitEngine]
commands:
  money:
    description: "Para ver o money atual"
    aliases: [coin, coins, solaryeconomy]
